import {
  GIAS,
  MASNUN,
  MITU,
  MOHSIN,
  RUMPA,
  RUSSEL,
  SAIMUM,
  SHANAIM,
  SUDARSHAN,
} from "assets/images/members";

export default [
  {
    name: "Abu Ashraf Masnun",
    designation: "Founder",
    id: "masnun",
    phone: "+8801711960803",
    email: "masnun@jukto.digital",
    image: MASNUN,
    linkedin: "masnun",
  },
  {
    name: "Saimum islam",
    designation: "Software Engineer",
    id: "saimum",
    phone: "+8801763706245",
    email: "saimumislam27@gmail.com",
    image: SAIMUM,
    linkedin: "saimum27",
  },
  {
    name: "Sudarshan Mondal",
    designation: "Software Engineer",
    id: "sudarshan",
    phone: "+8801961954926",
    email: "sudarshaana@gmail.com",
    image: SUDARSHAN,
    linkedin: "sudarshaana",
  },
  {
    name: "Gias Uddin",
    designation: "Software Engineer",
    id: "giasuddin",
    phone: "+8801630480451",
    email: "giasuddin.me90@gmail.com",
    image: GIAS,
    linkedin: "gias-uddin-762720144",
  },
  {
    name: "Rumpa Paul",
    designation: "Software Engineer",
    id: "rumpa",
    phone: "+8801795061160",
    email: "rumpapaul0201@gmail.com",
    image: RUMPA,
    linkedin: "rumpapaul",
  },
  {
    name: "S.M.Sha Naim Shourov ",
    designation: "Software Engineer",
    id: "shanaim",
    phone: "+8801728420051",
    email: "shanaim2k15@gmail.com",
    image: SHANAIM,
    linkedin: "shanaim",
  },
  {
    name: "Mohsin Al - Mamun",
    designation: "Software Engineer",
    id: "mohsin",
    phone: "+8801782396677",
    email: "oxgmohsin@gmail.com",
    image: MOHSIN,
    linkedin: "mohsinalmamun",
  },
  {
    name: "Shamima Nasrin",
    designation: "QA Engineer",
    id: "shamima",
    phone: "+8801625974820",
    email: "nasrin.shamima32@gmail.com",
    image: MITU,
    linkedin: "shamima-mitu-8763a7187",
  },
  {
    name: "Rasel Howlader",
    designation: "Office Assisstant",
    id: "rasel",
    phone: "+8801747978612",
    email: "mr0860344@gmail.com",
    image: RUSSEL,
  },
];
